#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/beryl-source-release.XXXXXX")"
trap 'rm -rf "${TMP_DIR}"' EXIT

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

expect_failure() {
  local output="$1"
  shift
  if "$@" >"${output}" 2>&1; then
    fail "command unexpectedly succeeded: $*"
  fi
}

assert_contains() {
  local file="$1"
  local expected="$2"
  grep -Fq -- "${expected}" "${file}" || fail "${file} did not contain: ${expected}"
}

assert_lock_ref() {
  local target="$1"
  local expected="$2"
  assert_contains "${target}/.beryl/lock.json" "\"sourceRef\": \"${expected}\""
}

# Seed Git metadata from HEAD, then overlay only the current checkout's tracked
# regular files. This makes a release fixture represent uncommitted candidate
# changes without accidentally packaging ignored or untracked workspace state.
create_candidate_checkout() {
  local destination="$1"
  local rel source destination_file

  git clone -q "${REPO_ROOT}" "${destination}"
  while IFS= read -r -d '' rel; do
    source="${REPO_ROOT}/${rel}"
    destination_file="${destination}/${rel}"
    [[ ! -L "${source}" ]] || fail "candidate fixture source must not contain symlinks: ${rel}"
    [[ -f "${source}" ]] || fail "candidate fixture tracked source is missing or unsupported: ${rel}"
    mkdir -p "$(dirname "${destination_file}")"
    cp -p "${source}" "${destination_file}"
  done < <(git -C "${REPO_ROOT}" ls-files -z)
  git -C "${destination}" add -u
}

# A local checkout must stage only release-tracked files.  These ignored and
# untracked artifacts previously crossed the component-directory boundary.
source_fixture="${TMP_DIR}/source-fixture"
create_candidate_checkout "${source_fixture}"
printf 'LOCAL_SECRET=must-not-install\n' >"${source_fixture}/.beryl/driver/config.env"
mkdir -p "${source_fixture}/.beryl/driver/__pycache__"
printf 'bytecode\n' >"${source_fixture}/.beryl/driver/__pycache__/driver.cpython-313.pyc"
printf 'local sentinel\n' >"${source_fixture}/.beryl/driver/local-sentinel.txt"

artifact_target="${TMP_DIR}/artifact-target"
sh "${REPO_ROOT}/install.sh" --source-dir "${source_fixture}" --target "${artifact_target}" --profile full
[[ ! -e "${artifact_target}/.beryl/driver/config.env" ]] || fail 'ignored config.env was installed'
[[ ! -e "${artifact_target}/.beryl/driver/__pycache__" ]] || fail 'generated bytecode was installed'
[[ ! -e "${artifact_target}/.beryl/driver/local-sentinel.txt" ]] || fail 'untracked sentinel was installed'
! grep -Fq '.beryl/driver/config.env' "${artifact_target}/.beryl/lock.json" || fail 'config.env was ledgered'
! grep -Fq '__pycache__' "${artifact_target}/.beryl/lock.json" || fail 'bytecode was ledgered'
! grep -Fq 'local-sentinel.txt' "${artifact_target}/.beryl/lock.json" || fail 'sentinel was ledgered'

# A directory that merely resembles a source release cannot claim the local
# checkout interface; it has no tracked release inventory.
non_git_source="${TMP_DIR}/non-git-source"
mkdir -p "${non_git_source}/.beryl"
cp "${REPO_ROOT}/.beryl/beryl.components.json" "${non_git_source}/.beryl/"
non_git_target="${TMP_DIR}/non-git-target"
expect_failure "${TMP_DIR}/non-git.out" sh "${REPO_ROOT}/install.sh" \
  --source-dir "${non_git_source}" --target "${non_git_target}" --profile minimal
assert_contains "${TMP_DIR}/non-git.out" 'local --source-dir must be a Git checkout'
[[ ! -e "${non_git_target}" ]] || fail 'non-Git source validation mutated the target'

# A tracked symlink is not a release file: accepting it would let a local
# checkout stage content from outside its declared component surface.
symlink_source="${TMP_DIR}/symlink-source"
create_candidate_checkout "${symlink_source}"
ln -s /etc/hosts "${symlink_source}/.beryl/driver/tracked-link.txt"
git -C "${symlink_source}" add .beryl/driver/tracked-link.txt
git -C "${symlink_source}" -c user.email=tests@example.invalid -c user.name='Beryl tests' \
  commit -qm 'tracked source symlink fixture'
symlink_target="${TMP_DIR}/symlink-target"
expect_failure "${TMP_DIR}/symlink-source.out" sh "${REPO_ROOT}/install.sh" \
  --source-dir "${symlink_source}" --target "${symlink_target}" --profile full
assert_contains "${TMP_DIR}/symlink-source.out" 'tracked source file missing or is a symlink'
[[ ! -e "${symlink_target}" ]] || fail 'tracked source symlink validation mutated the target'

# Remote lifecycle sources are immutable release artifacts. Branches and tags,
# and even a full commit without an archive digest, fail before target creation.
remote_branch_target="${TMP_DIR}/remote-branch-target"
expect_failure "${TMP_DIR}/remote-branch.out" sh "${REPO_ROOT}/install.sh" \
  --target "${remote_branch_target}" --ref main
assert_contains "${TMP_DIR}/remote-branch.out" 'remote lifecycle requires --ref to be a full 40-character commit SHA'
[[ ! -e "${remote_branch_target}" ]] || fail 'remote branch refusal created a target'

remote_tag_target="${TMP_DIR}/remote-tag-target"
expect_failure "${TMP_DIR}/remote-tag.out" sh "${REPO_ROOT}/install.sh" \
  --target "${remote_tag_target}" --ref v1.0.0
assert_contains "${TMP_DIR}/remote-tag.out" 'remote lifecycle requires --ref to be a full 40-character commit SHA'
[[ ! -e "${remote_tag_target}" ]] || fail 'remote tag refusal created a target'

remote_digest_target="${TMP_DIR}/remote-digest-target"
remote_sha='0123456789abcdef0123456789abcdef01234567'
expect_failure "${TMP_DIR}/remote-digest.out" sh "${REPO_ROOT}/install.sh" \
  --target "${remote_digest_target}" --ref "${remote_sha}"
assert_contains "${TMP_DIR}/remote-digest.out" 'remote lifecycle requires --expected-sha256'
[[ ! -e "${remote_digest_target}" ]] || fail 'remote digest refusal created a target'

# A fake HTTPS transport verifies the accepted path without network access. It
# serves the candidate manifest/archive only after installer HTTPS validation.
remote_candidate="${TMP_DIR}/remote-candidate"
create_candidate_checkout "${remote_candidate}"
remote_archive="${TMP_DIR}/remote-candidate.tar.gz"
tar -czf "${remote_archive}" -C "${TMP_DIR}" "$(basename "${remote_candidate}")"
remote_digest="$(sha256sum "${remote_archive}" | awk '{print $1}')"
remote_bin="${TMP_DIR}/remote-bin"
mkdir -p "${remote_bin}"
cat >"${remote_bin}/curl" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
output=''
url=''
while (($#)); do
  case "$1" in
    -o) output="$2"; shift 2 ;;
    *) url="$1"; shift ;;
  esac
done
case "${url}" in
  */raw/*)
    printf 'raw manifest endpoint invoked: %s\n' "${url}" >>"${BERYL_REMOTE_LOG}"
    exit 91
    ;;
  *) cp "${BERYL_REMOTE_ARCHIVE}" "${output}" ;;
esac
EOF
chmod +x "${remote_bin}/curl"
remote_success_target="${TMP_DIR}/remote-success-target"
env PATH="${remote_bin}:${PATH}" BERYL_REMOTE_LOG="${TMP_DIR}/remote-transport.log" \
  BERYL_REMOTE_ARCHIVE="${remote_archive}" sh "${REPO_ROOT}/install.sh" --target "${remote_success_target}" \
  --profile minimal --ref "${remote_sha}" --expected-sha256 "${remote_digest}" \
  --archive-url "https://mock.invalid/archive/${remote_sha}"
assert_lock_ref "${remote_success_target}" "${remote_sha}"
[[ ! -e "${TMP_DIR}/remote-transport.log" ]] || fail 'remote install fetched an unverified raw manifest'

# Updates lock their original source ref.  A later default must not silently
# drift to the installer default ref; only an explicit --ref replaces it.
ref_target="${TMP_DIR}/ref-target"
sh "${REPO_ROOT}/install.sh" --source-dir "${REPO_ROOT}" --target "${ref_target}" \
  --profile minimal --ref release-candidate-1
assert_lock_ref "${ref_target}" release-candidate-1
sh "${REPO_ROOT}/install.sh" --update --source-dir "${REPO_ROOT}" --target "${ref_target}" \
  >"${TMP_DIR}/locked-ref-update.out" 2>&1
assert_contains "${TMP_DIR}/locked-ref-update.out" 'source ref release-candidate-1'
assert_lock_ref "${ref_target}" release-candidate-1
sh "${REPO_ROOT}/install.sh" --update --source-dir "${REPO_ROOT}" --target "${ref_target}" \
  --ref release-candidate-2
assert_lock_ref "${ref_target}" release-candidate-2
sh "${REPO_ROOT}/install.sh" --update --source-dir "${REPO_ROOT}" --target "${ref_target}" \
  >"${TMP_DIR}/replacement-ref-update.out" 2>&1
assert_contains "${TMP_DIR}/replacement-ref-update.out" 'source ref release-candidate-2'
assert_lock_ref "${ref_target}" release-candidate-2

# A skipped root contract is a durable selection.  Update reuses that policy
# rather than unexpectedly requiring a second conflict flag.
root_target="${TMP_DIR}/root-policy-target"
mkdir -p "${root_target}"
printf 'target-owned AGENTS contract\n' >"${root_target}/AGENTS.md"
sh "${REPO_ROOT}/install.sh" --source-dir "${REPO_ROOT}" --target "${root_target}" \
  --profile minimal --root-conflict skip
assert_contains "${root_target}/.beryl/lock.json" '"rootConflictPolicy": "skip"'
assert_contains "${root_target}/.beryl/lock.json" '"skip:AGENTS.md"'
assert_contains "${root_target}/.beryl/lock.json" '"preservedRootContractDigestsVersion": 1'
sh "${REPO_ROOT}/install.sh" --update --source-dir "${REPO_ROOT}" --target "${root_target}" \
  >"${TMP_DIR}/preserved-root-contract-update.out" 2>&1
grep -Fq 'beryl: update complete readiness=ready-with-preserved-external-contracts' \
  "${TMP_DIR}/preserved-root-contract-update.out" || \
  fail 'preserved root-contract update reported an unqualified completion'
assert_contains "${root_target}/.beryl/lock.json" '"rootConflictPolicy": "skip"'
[[ "$(<"${root_target}/AGENTS.md")" == 'target-owned AGENTS contract' ]] || \
  fail 'locked skip policy replaced the target-owned shim during update'

# An update must not recalculate a preserved-contract digest after the host
# changed that contract. It fails before staging and retains the prior lock.
printf 'changed target-owned AGENTS contract\n' >"${root_target}/AGENTS.md"
expect_failure "${TMP_DIR}/changed-root-contract-update.out" sh "${REPO_ROOT}/install.sh" \
  --update --source-dir "${REPO_ROOT}" --target "${root_target}"
assert_contains "${TMP_DIR}/changed-root-contract-update.out" \
  'preserved external root contract changed since install: AGENTS.md'

printf 'source release tests passed\n'
